SELECT* FROM INHABITANT 
SELECT * FROM INHABITANT WHERE STATE = 'friendly'
SELECT * FROM INHABITANT WHERE STATE = 'friendly' AND JOB = 'weaponsmith'
SELECT * FROM INHABITANT WHERE STATE = 'friendly' AND JOB LIKE '%smith'
SELECT PERSONID FROM INHABITANT WHERE NAME = 'Stranger'